"""empty message

Revision ID: ad43d1a4fa2a
Revises: 87c44adf09cd
Create Date: 2021-12-17 22:08:07.032616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad43d1a4fa2a'
down_revision = '87c44adf09cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'aboutMe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('aboutMe', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
