"""empty message

Revision ID: 87c44adf09cd
Revises: 09dec8d064ed
Create Date: 2021-12-17 22:06:34.440642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c44adf09cd'
down_revision = '09dec8d064ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('lastName', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('aboutMe', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'aboutMe')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###
